# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: "https://AxelS83.github.io"
baseurl: "/foerderverein-kyritzschule.github.io"
title: "Förderverein der Kyritzschule Darmstadt e.V."
description: "Der Förderverein der Kyritzschule Darmstadt e.V. unterstützt schulische Projekte und Gemeinschaft."
permalink: pretty
logo: "/pictures/logo.png" # null #"https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Über uns
  url: /
- title: Mitglied werden
  url: /mitglied/
- title: Spenden
  url: /spenden/ 
- title: Projekte
  url: /blog/
- title: Kontakt
  url: /kontakt/

# Footer nav
navigation_footer:
#- title: Back to top
#  url: "#top"
- title: Impressum
  url: /impressum/

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
